const cities = [
    "Adana",
    "Adıyaman",
    "Ağrı",
    "Amasya",
    "Ankara",
    "Antalya",
    "Artvin",
    "Aydın",
    "Balıkesir",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolu",
    "Burdur",
    
    "Bursa",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Edirne",
    "Elazığ",
    "Gaziantep",
    "Erzurum",
    "İstanbul",
    "İzmir",
    "Kars ",
    "Kastamonu",
    "Kayseri",
    "Kırklareli",
    "Kırşehir",
    "Kocaeli",
    "Konya ",
    "Malatya ",
    "Manisa",
    "Mardin ",
    "Muğla ",
    "Nevşehir",
    "Niğde ",
    "Ordu ",
    "Rize ",
    "Sakarya ",
    "Samsun ",
    "Siirt ",
    "Sinop ",
    "Tekirdağ ",
    "Trabzon ",
    "Tunceli ",
    "Van ",
    "Yozgat ",
    "Batman ",
    "Batman ",
    "Ardahan ",
    "Iğdır ",
    "Yalova "

];